### ISSUE TITLE
Hot key for toggeling dark mode

### ISSUE THREAD

**Issue by rugk** [rugk/website-dark-mode-switcher#10]
## Background

As a user I may want a quick way to trigger the mode without even clicking.

## Proposed solution

-> hot key/shortcut

## Alternatives

N/A

## Additional context

If possible, do not set a default. Users can do so in the Firefox settings.

If you like this idea, please upvote this issue!
Also feel free to send PR's, this is a "good first issue"! :smiley:

**Comment by jugendhacker** [comment]
I'm trying to fiddle into this... is it right to use [this](https://github.com/TinyWebEx/AddonSettings/blob/b3da318002a1fbbdf15aa93be8b0e062b9c6ff69/AddonSettings.js#L271) to save the setting?

**Comment by rugk** [comment]
First of all, thanks for taking this up. :smiley: 

But nah, it rather is not. A better hint may be https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands.

**Comment by rugk** [comment]
@jugendhacker  Are you still interested in it? If not, that's no problem, just add a notice, so I know what the current status of this issue is.

**Comment by jugendhacker** [comment]
I currently have not much time.... so better do it yourself

**Comment by rugk** [comment]
Yeah, fine, I've unassigned you so anyone else can pick it up or I'll may do it by myself at some point. :smiley:
