### ISSUE TITLE
white extension icon for dark firefox themes?

### ISSUE THREAD

**Issue by jorjio** [rugk/website-dark-mode-switcher#25]
## Background
https://i.imgur.com/QBJAxsI.png

**Comment by rugk** [comment]
FYI You can also embed images directly on GitHub.

The extension already uses a white icon for dark themes. However, technically, this is only possible for the toolbar icon, not for the one in about:addons you've shown.

Also next time please do fill the "new issue" template. This should have been suggested to you before/when opening a new issue.
