### ISSUE TITLE
Doesn't work with stylesheets imported with @import

### ISSUE THREAD

**Issue by Justin-CB** [rugk/website-dark-mode-switcher#26]
I was testing this extension on my own site(<a href="justinbesterportfolio.xp3.biz">justinbesterportfolio.xp3.biz</a>), but it didn't use my styles that I defined with a `prefers-color-scheme: dark` query. I <code>&lt;link></code> a dummy stylesheet that `@import`s the real stylesheet, but presumably, this would apply to all `@import`ed stylesheets.

**Comment by rugk** [comment]
Hmm, actually it uses the browser's parsed CSS tree. So I see no integrated issue. Could you probably use the "Problem with a specific website" issue template to report a bug?.

**Comment by rugk** [comment]
Okay, apparently done in https://github.com/rugk/website-dark-mode-switcher/issues/28 thanks 😃
