### ISSUE TITLE
Inconsistent Application on New Tabs

### ISSUE THREAD

**Issue by ConnorJC3** [rugk/website-dark-mode-switcher#32]
## Bug description
The extension often fails to apply the dark mode when visiting websites from a new tab.

## Steps to reproduce
1. Start with a fresh firefox profile
2. Set `ui.systemUsesDarkTheme` to `0`
3. Install this addon from AMO
4. Open a new tab
5. Visit a test website (ex: https://webkit.org/) via the URL bar

### Actual behavior
Dark mode often is not applied (but refreshing fixes it and applies the dark mode). Not 100% consistent, but happens to me roughly 40%-50% of the time when testing.

### Expected behavior
Dark mode is forced.

## System

Operating system and version: Linux arch 5.11.2-arch1-1
Browser and version: Firefox Nightly 88.0a1 (2021-03-02) (64-bit) [note: happens on previous versions too]
Add-on version: 1.2 [latest on AMO as of time of issue]

**Comment by rugk** [comment]
Interesting, I have never seen that and also cannot reproduce it currently. It sometimes fails to catch existing tabs when installed/enabled, but when I visit a page via a new tab it

Maybe it's a race condition somehow. Anyone who experiences this issue, feel free to look into the code and spot a potential issue.
Also maybe the `about:debugging` logs for the add-on would be useful.

Here is how to find the debug logs:
1. [Open a new tab and go to `about:debugging` -> "This Firefox"](https://extensionworkshop.com/documentation/develop/debugging/#developer-tools-toolbox).
2. Find this add-on there and click "Debug".
3. In the web console you get there, there may be logs. (Look at these logs before you reproduce the issue and clear them, to only provide the logs when the error happens.)

Thanks in advantage for helping.

**Comment by ConnorJC3** [comment]
When visiting failing page I get errors like this in the console:

```
Uncaught (in promise) Error: Nothing to auto-fill.
    doAutoFill moz-extension://900e9628-cf15-411f-838c-fb459a7e8f02/background.js:22569
    fulfilled moz-extension://900e9628-cf15-411f-838c-fb459a7e8f02/background.js:22421

Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.
```

However, I seem to receive them as well on pages that _do_ work. Pages that do work will output a

```
Got message 
Object { type: "insertCss", css: "LOTS_OF_CSS_HERE" } from Object { id: "dark-mode-website-switcher@rugk.github.io", envType: "content_child", frameId: 0, url: "SOME_URL_HERE", contextId: 2199023255694, tab: {…} }

tab 27 SOME_URL_HERE injection worked
```

Pages that do not work never output this.

**Comment by ConnorJC3** [comment]
Ok, this was annoying me enough I cloned the repo to do some local debugging. For me it fails specifically on this if statement:

https://github.com/rugk/website-dark-mode-switcher/blob/ee45d2006054a190e7815b6d120818458f18a375/src/content_scripts/applyColorSchemeCss.js#L195-L199

Putting a `console.log` before the if statement it prints, and then putting one in each branch it doesn't print.

Further testing: I tried beginning `applyWantedStyle` with this code:
```
console.log('BEFORE');
console.log(functionalMode);
console.log('AFTER');
```
On broken pages, only the 'BEFORE' prints (on working pages, all of it prints with `functionalMode` turning out to be `false`)

**Comment by ConnorJC3** [comment]
Update: I have determined that when this code runs that `COLOR_STATUS` does not exist: https://github.com/rugk/website-dark-mode-switcher/blob/ee45d2006054a190e7815b6d120818458f18a375/src/background/modules/CssAnalysis.js#L40

This causes the line after it to never execute which later causes the content script to explode.

**Comment by ConnorJC3** [comment]
Final update: By using `console.log`s I have confirmed that in the failed case this code runs AFTER the above injected code:
https://github.com/rugk/website-dark-mode-switcher/blob/ee45d2006054a190e7815b6d120818458f18a375/src/content_scripts/common.js#L18-L24

As far as I can tell this method of injecting prefs seems to be race-y, as in there's no guarantee that `browser.contentScripts.register` scripts execute before those from `content_scripts` in the `manifest.json`. Just on typical setups you win the race consistently enough it isn't noticeable, but for me I lose the race on newly opened tabs for some reason.

**Comment by rugk** [comment]
Oh, thanks a lot for debugging and documenting that/your progress!
Do you plan to make a PR or do you have a suggestion/idea what could be improved/made to fix this?

**Comment by ConnorJC3** [comment]
@rugk I don't have any addon dev experience, to be honest my js knowledge and the getting started guide allowed me to fumble my way through this enough to discover the issue. One solution I thought of that might work is to only slip in the string in `CssAnalysis.js` and read from `COLOR_STATUS` later (I believe the order in `content_scripts` is consistent, so `common.js` will always have executed in time).

However, I'm worried that just leaves open a rarer race condition where the injected code runs way later than the other scripts and causes this issue still. I'm trying to find any documentation on ordering between `browser.contentScripts.register` and `content_scripts` but am yet to find anything.

**Comment by rugk** [comment]
Does it help [if you set `matchAboutBlank` to `false`](https://github.com/rugk/website-dark-mode-switcher/blob/ee45d2006054a190e7815b6d120818458f18a375/src/background/modules/CssAnalysis.js#L45)?
I wonder why I have even set it to true given thios add-on is useless on `about:newtab` pages anyway.
Also note we try toi load everything as fast as possible with [`runAt: "document_start"`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_scripts#run_at). Given it's the same for the manifest and interactively injected stuff, I can totally see that this may be causing the issue.

**Comment by rugk** [comment]
Okay note  `enableSettingInjection` only runs when you change the option or once when the add-on is loaded.
If it is registered, Firefox should then handle the order in which it loads.

**Comment by rugk** [comment]
Okay, I made something, @ConnorJC3 could you try this?
https://github.com/rugk/website-dark-mode-switcher/pull/34

BTW if you want to debug the injected snippet [just place a `debugger;` statement inside it here](https://github.com/rugk/website-dark-mode-switcher/pull/34/files#diff-13ac072ebc051aff4cef5db017e908b784d46b1d6e663da70d08d74ecb83bf0cR62) and on the tab where the snippet is injected it should go there in the debugger.

**Comment by ConnorJC3** [comment]
Sadly a `debugger;` statement is completely useless, because I can only use it to observe the cases where I win the race (by the time I am even physically able to click "Step Into" in the debugger the other scripts have long executed).

@rugk found two mistakes in the new version:

1. `if (COLOR_STATUS) {` will cause the code to eat a `ReferenceError: COLOR_STATUS is not defined` if you lose the race rather than correctly rescheduling for 100ms from now. Using `if (typeof COLOR_STATUS !== 'undefined') {` works as it is intended.

2. In `setSettings(functionalMode, fakedColorStatusNewString);` it should actually use `functionalModeNew`, as `functionalMode` will be null when the code from the `setTimeout` runs (I have no idea why this is the case but console.log and the debugger tell me it is /shrug).

**Comment by rugk** [comment]
@ConnorJC3 Oh, thanks! Feel free to comment this as a proper review in the PR, as it's easier to track then.
I'll have a look soon.
