### ISSUE TITLE
Support forcing light mode

### ISSUE THREAD

**Issue by fastloris** [rugk/website-dark-mode-switcher#33]
## Background
My system is dark mode by default, but occasionally I want to force light mode. I'd love if I could use this to change the color preference the other way around.

## Proposed solution
Exact same behavior, but it inverts the current setting instead of forcing dark mode.

## Alternatives
Couldn't find any others.

## Additional context
Maybe this is possible, but if so I couldn't figure out how to make it work and the description of the extension seems to at least in the add-on site describe it as only being able to force dark mode.

**Comment by rugk** [comment]
Duplicate of https://github.com/rugk/website-dark-mode-switcher/issues/5

**Comment by rugk** [comment]
Es explained there and in the Readme, it's currently unfortunately not possible due to how the add-on is designed and the limitations of the WebExtension APIs.
