### ISSUE TITLE
https://ar.al/ Vimeo Embed Inverted

### ISSUE THREAD

**Issue by elsiehupp** [rugk/website-dark-mode-switcher#39]
**Affected website:** https://ar.al/

## Bug description
On the homepage of the website there is a Vimeo embed. With Dark Website Forcer enabled and toggled on, the embed is inverted. When Dark Website Forcer is disabled or toggled off, the website correctly reflects the system settings (on Firefox 92.0 on macOS 11.5.2).

## Steps to reproduce

1. Go to https://ar.al/
2. Toggle Dark Website Forcer on and off
3. The website appears correctly (dark or light) with Dark Website Forcer off and the Vimeo embed is inverted with Dark Website Forcer on, regardless.

### With macOS "Light Appearance" and Dark Website Forcer toggled off:
<img width="1024" alt="Light mode (default)" src="https://user-images.githubusercontent.com/9206310/133932728-96361422-fab0-4ac4-98bd-0c345e2cf98a.png">

### With macOS "Dark Appearance" and Dark Website Forcer toggled off:
<img width="1024" alt="Dark mode (default)" src="https://user-images.githubusercontent.com/9206310/133932820-78394b80-b49b-4dd2-a637-7ac111546a3b.png">

### With any macOS Appearance and Dark Website Forcer toggled on:
<img width="1024" alt="Inverted Vimeo Embed" src="https://user-images.githubusercontent.com/9206310/133932637-5142f0a9-cd16-458e-bed5-d0faa0aeba4c.png">

### Actual behavior
See above.

### Expected behavior
Nothing should happen.

## System

Operating system and version: macOS 11.5.2
Browser and version: Firefox Firefox 92.0
Add-on version: 1.2

## Possible solution

idk. This doesn't seem like something that should happen in the first place.

**Comment by rugk** [comment]
Hu, that looks fun! :sweat_smile:

**Comment by rugk** [comment]
Hi, I have great news for you! According to my testing, the latest [v2.0 release](https://github.com/rugk/website-dark-mode-switcher/releases/tag/v2.0) fixes this issue due to the way it now uses a completely new API to do "dark-mode-changing" "properly". For more information, please see the release notes. If the issue should not be fixed, please let me know.
