### ISSUE TITLE
Bootstrap 5 Dark Mode has incorrect gradient/fades applied

### ISSUE THREAD

**Issue by nogweii** [rugk/website-dark-mode-switcher#40]
**Affected website:** Anyone using the https://github.com/vinorodrigues/bootstrap-dark-5 CSS library

## Bug description
Something to do with the removal of the light mode CSS causes an ugly white fade out to be left behind, when it should be the opposite.

## Steps to reproduce
1. Go to https://vinorodrigues.github.io/bootstrap-dark-5/examples/cheatsheet-dark.html

### Screencast/Screenshots

<table>
<tr>
<td>

![image](https://user-images.githubusercontent.com/14547/142834212-b7eef0e7-e916-42ca-a2b9-7bfc7edafd2c.png)

Rendering correctly in an empty Firefox profile and dark mode set in the preferences

</td>
<td>

![image](https://user-images.githubusercontent.com/14547/142834097-e65a29af-40ed-4761-baa3-123c56b65dab.png)

Rendered incorrectly in Firefox with `privacy.resistFingerprinting` and this extension installed

</td>
</tr>
</table>

### Expected behavior
I'd hope it's possible to fix this, and not leave the broken fades.

## System

Operating system and version: Windows 10
Browser and version: Firefox 94.0.1
Add-on version: 1.2

**Comment by rugk** [comment]
So the issue only happens with `privacy.resistFingerprinting`?

Hmm, I have no clue why that influences the stuff.
