### ISSUE TITLE
Support forcing light style

### ISSUE THREAD

**Issue by rugk** [rugk/website-dark-mode-switcher#5]
As explained [in the Readme](https://github.com/rugk/website-dark-mode-switcher#important-limitations) and in the descriptions etc. of AMO, we can only try to force websites to have a dark style.

We cannot force a light style, mostly, as most websites won't use `prefers-color-scheme: light`.

**Comment by rugk** [comment]
Blocked by https://bugzilla.mozilla.org/show_bug.cgi?id=1547818

**Comment by sbrl** [comment]
I think this might be my bug. I've got the `prefers-color-scheme: dark` enabled via `ui.systemUsesDarkTheme = 1` (I think that's the property name? I can't remember), so when I  try to use this extension, nothing happens - since it can't unset the dark theme setting.

**Comment by rugk** [comment]
Yes, of course, it only can force the dark mode. So what is your concern here?

**Comment by sbrl** [comment]
I was falsely under the impression that it could toggle dark mode, regardless of whether I had it set by default or not.

I'll just sit subscribe to this bug (and the Bugzilla one on the FF bug tracker) for updates.

**Comment by rugk** [comment]
Yep, thanks. You'll see that the API(s) does not really allow this.

I tried to make it very clear in the add-on description etc. that it actually is _not_ possible to force a light style. (for many websites, at least, as likely no one uses `prefers-color-scheme: light` on their site)

**Comment by sbrl** [comment]
I must have missed that description. I do have a peristent problem whereby I don't fully read the middle of sentences etc..... :P

**Comment by rugk** [comment]
Hi, I have great news for you! According to my testing, the latest [v2.0 release](https://github.com/rugk/website-dark-mode-switcher/releases/tag/v2.0) fixes this issue due to the way it now uses a completely new API to do "dark-mode-changing" "properly". For more information, please see the release notes. If the issue should not be fixed, please let me know.
