### ISSUE TITLE
Solution for Dark Mode Website Switcher not working with arkenfox's user.js

### ISSUE THREAD

**Issue by RevolverTexture** [rugk/website-dark-mode-switcher#51]
**pref that break this extension**: `user_pref("privacy.resistFingerprinting", true);` 
**breakage**:  websites prefer light mode than dark mode
**solution**: change  `user_pref("privacy.resistFingerprinting", true);` to `false`

Submiting it here if anyone will have this issue as well.

**Comment by rugk** [comment]
Duplicate of #48

**Comment by rugk** [comment]
…I guess… :upside_down_face:
